services:
  - type: web
    name: CafeGaleria
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist/frontEnd/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html